### ISSUE TITLE
SMTP configurable authentication mechanism

### ISSUE THREAD

**Issue by YKWeyer** [bitnami/bitnami-docker-matomo#46]
**Description**

When using `SMTP_*` environment variables to configure access to a SMTP server, the `PLAIN` authentication mechanism is used and can't be changed.

**Steps to reproduce the issue:**

1. Configure the matomo container to connect to a SMTP server with no `PLAIN` mechanism allowed
2. Try to send an email using `/opt/bitnami/matomo/console core:test-email (your-email)`

**Describe the results you received:**

It fails with message:
> [Zend_Mail_Protocol_Exception]          
> 5.7.4 Unrecognized authentication type  

**Describe the results you expected:**

It _should_ be possible to connect to SMTP servers using `LOGIN` or `CRAM-MD5` authentication mechanism.

**Additional information you deem important (e.g. issue happens only occasionally):**

You might consider adding a new environment variable (`SMTP_AUTH`?) to let the user define which mechanism should be used: 

```diff 
--- a/com.bitnami.matomo/helpers.js
+++ b/com.bitnami.matomo/helpers.js
@@ -73,7 +73,7 @@ $app.helpers.configureSMTP = function(smtpData) {
             host: smtpData.host,
             username: smtpData.user,
             password: smtpData.password,
-            type: 'Plain',
+            type: smtpData.auth,
             encryption: smtpData.protocol,
         };
         $file.ini.set($file.join('config', 'config.ini.php'), 'mail', smtpConfig);

```

```diff 
--- a/com.bitnami.matomo/nami.json
+++ b/com.bitnami.matomo/nami.json
@@ -100,6 +100,16 @@
         ""
       ]
     },
+    "smtpAuth":         {
+      "description": "Authentication mechanism to use for SMTP [Plain, Login, Crammd5]",
+      "default": "Plain",
+      "type": "choice",
+      "validValues":             [
+        "Plain",
+        "Login",
+        "Crammd5"
+      ]
+    },
     "nonRootSystemUser":         {
       "description": "System user for Matomo files",
       "value": "bitnami"
```
```diff
--- a/com.bitnami.matomo/main.js
+++ b/com.bitnami.matomo/main.js
@@ -41,6 +41,7 @@ $app.postInstallation = function() {
             host: $app.smtpHost,
             port: $app.smtpPort,
             protocol: $app.smtpProtocol,
+            auth: $app.smtpAuth,
         };
 
         $app.info(`Installing ${$app.name}. It could take some minutes...`);
```

(I'd happily run tests again it and submit a merge request, but I didn't find it anywhere. I guess this isn't in any public repository?)

**Comment by carrodher** [comment]
Hi, thanks for the suggestion.

It is true, we have different configurable values but not the authentication method. I just created an internal task to add an env. variable to allow the configuration through Dockerfile or docker-compose.

Unfortunately, the repository where we should implement those changes is not public, but the changes are really close to what you are suggesting so thank you for your research.

I will update this thread once the new matomo image including those changes appears in the registry.

**Comment by YKWeyer** [comment]
Thank you @carrodher !

> Unfortunately, the repository where we should implement those changes is not public

Would Bitnami consider making the components part public? As far as I understand, those files can be read in the containers (under `/root/.nami/components`). Unless there is some Bitnami magic involved somewhere? :smile: 

It is somewhat related to another interrogation of mine: the [releases](https://github.com/bitnami/bitnami-docker-matomo/releases) (as well as associated commits) contains no Changelog. 
Is there really no way to communicate what changed between two base image versions? In case of security patches or important bufixes, it would be really helpful to identify them as such

**Comment by carrodher** [comment]
Hi, 

> Would Bitnami consider making the components part public? As far as I understand, those files can be read in the containers (under `/root/.nami/components`). Unless there is some Bitnami magic involved somewhere? 😄

The repo itself is private although part of the code is inside each container this is a tool named `nami` based on NodeJS that we used for the configuration logic in our containers. At this moment we are moving from this tool to bash logic so this is something temporary.
For example, at this time we moved to the new logic all our infrastructure containers, you can check for example Apache, now in the GitHub repository there are other folders with this logic as bash scripts: https://github.com/bitnami/bitnami-docker-apache/tree/master/2.4/debian-9
We are working on moving all the containers, not only the infrastructure ones.
 
> It is somewhat related to another interrogation of mine: the [releases](https://github.com/bitnami/bitnami-docker-matomo/releases) (as well as associated commits) contains no Changelog.
> Is there really no way to communicate what changed between two base image versions? In case of security patches or important bugfixes, it would be really helpful to identify them as such

It is not easy to create a changelog because the container image is updated automatically every day. From one day to another our CI/CD system just build the image on top of the latest Debian base image, in that way we ensure there are no packages with vulnerabilities in our base image (at least if the CVE was fixed by Debian).
Apart from that, from time to time a new release can contain new changes, for example, the one about the SMTP mechanism we are discussing here. We have a section in the README about ["Notable changes"](https://github.com/bitnami/bitnami-docker-matomo#notable-changes). 
If the changes included in a new revision are important (important for various reasons, not a specific one) we add a new item in this list.

**Comment by carrodher** [comment]
Hi, the auth mechanism environment variable should be ready. It was added to the Oracle and Debian image in the following commits: https://github.com/bitnami/bitnami-docker-matomo/commit/f3262a55ee84802bbd479392b024a80371340c2c https://github.com/bitnami/bitnami-docker-matomo/commit/13a674afcf283263ad161d7afe913a36766b4ea5

[Here](https://github.com/bitnami/bitnami-docker-matomo#smtp-configuration) you can find the README updated with the new parameter.

It was tested using the default method ('Plain'), feel free to provide feedback if you try it using other configurations.

Thank you very much for reporting this issue.

**Comment by YKWeyer** [comment]
Wow, that was fast!

I'll test it on Monday, and close the issue if the latest docker image solves the problem. Thank you very much :+1:

**Comment by YKWeyer** [comment]
Hi @carrodher , 

I tested it with the Login mechanism, and i can happily report it works as expected :+1: 

Thank you very much for your fix!
