### ISSUE TITLE
Change MATOMO_SMTP_USER and MATOMO_SMTP_PASSWORD to not mandatory

### ISSUE THREAD

**Issue by MarcelMYSchmitt** [bitnami/bitnami-docker-matomo#72]
Hi,

i've seen that there is already an issue with the privileged port: https://github.com/bitnami/bitnami-docker-matomo/issues
My question is if you can change the USER and PASSWORD environment variables so they do not have to be set.

You will not believe me but there are also on premise SMTP servers which do not have any authentication ;) 

Greetings,
Marcel

**Comment by FraPazGal** [comment]
Hello @MarcelMYSchmitt,

Thanks for bringing this up! We are aware that some SMTP servers don't need authentication and we are currently working on making user/password SMTP configuration optional throughout our whole catalog, matomo included. I'll label this issue as `on-hold` and come back as soon as there are any news.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-matomo#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
