### ISSUE TITLE
Docker hub gives 404

### ISSUE THREAD

**Issue by fletcher91** [bitnami/bitnami-docker-matomo#74]
Don't know why, tested some other bitnami repos, which all work.

Go to https://hub.docker.com/r/bitnami/matomo
Get 404 page

![image](https://user-images.githubusercontent.com/1248467/103763433-1fee1300-501a-11eb-8883-13d82b11c6fa.png)

**Comment by FraPazGal** [comment]
Hello @fletcher91,

Thanks for using our containers! I have been able to reproduce this on those devices with an adblocker activated. It seems they an issue with that repository in particular. Could that be the source of your 404 as well?

**Comment by Findus23** [comment]
Hi,

I explained the reason for this here:
https://www.reddit.com/r/matomo/comments/kfp96t/all_nonofficial_matomo_images_removed_from_docker/ggqd0em/

Long story short: The page is not really a 404, but most adblockers block the API request it tries to do because it contains `matomo` and this causes the page to fall back to showing the 404 error message.

This pull request should fix the blocking rules: https://github.com/easylist/easylist/pull/6797

**Comment by FraPazGal** [comment]
Thanks for the heads up @Findus23! We'll need to be careful with adblockers until then 😄

**Comment by fletcher91** [comment]
Ha, didn't expect that. Tested it on multiple devices/connections as well, but I had adblocker on those as well

**Comment by Findus23** [comment]
Just FYI: The issue should now be fixed with https://github.com/easylist/easylist/commit/3293ab6042b5d1927a67afdd838b5ff38e478061
