### ISSUE TITLE
Replicated instances and volumes

### ISSUE THREAD

**Issue by nielssj** [bitnami/bitnami-docker-matomo#78]
I am deploying this image in a Kubernetes cluster which is replicated across 2 zones. I am just using the Matomo image (database is already present). High availability is a requirement, so minimum one replica of Matomo in each zone. I don't have ReadWriteMany volumes available. Basic functionality seems to work, but it is unclear to me which parts of Matomo depend on the persistent volumes being synchronized or even persisted at all. I would prefer to keep this as stateless as possible (outside DB) and am willing to accept a limited feature set. Can you advice whether this could work at all? Which features depend on the `/bitname` volume? And what are the consequences if I clear/reset them on restart/update? (Given that I've configured the instance through environment variables)

**Comment by juan131** [comment]
Hi @nielssj 

Matomo is not a stateless application and it doesn't follow the [12 Factor App](https://12factor.net/) methodology as modern Cloud Native Apps do. Therefore, it's not easy to achieve what you want.

The approach we followed when designing this image consisted on moving Matomo configuration and data to a different path where a volume can be mounted to save it. This way, although we installed the app at `/opt/bitnami/matomo`, there are certain configuration directories that are actually saved at `/bitnami/matomo` and referenced using symlinks. Find info about how we do it in the links below:

- https://github.com/bitnami/bitnami-docker-matomo/blob/master/4/debian-10/rootfs/opt/bitnami/scripts/matomo-env.sh#L71
- https://github.com/bitnami/bitnami-docker-matomo/blob/master/4/debian-10/rootfs/opt/bitnami/scripts/libmatomo.sh#L193
- https://github.com/bitnami/bitnami-docker-matomo/blob/master/4/debian-10/rootfs/opt/bitnami/scripts/libmatomo.sh#L200
- https://github.com/bitnami/bitnami-docker-matomo/blob/master/4/debian-10/prebuildfs/opt/bitnami/scripts/libpersistence.sh

In order to scale Matomo, you need to ensure that the configuration and data is synced between Matomo replicas. That's why you'll have to use a NFS server and RWX volumes, so you can sync the data and mount the same volume in every replica. In the past, we wrote an article explaining how to do this using the WordPress Helm chart and the NFS Server Provisioner chart, see:

- https://engineering.bitnami.com/articles/scaling-wordpress-in-kubernetes.html

That might be helpful for you.

**Comment by nielssj** [comment]
Hi @juan131 
Thank you so much for your swift and thorough response. This is extremely helpful to me.
I think the official article on matomo.org ([Does Matomo work in a load balanced environment?](https://matomo.org/faq/new-to-piwik/faq_134/)) has mislead me, as it does not make it clear that you need proper NFS to back it. I will be sending them some feedback.
I've wasted a lot of time trying to make this work. We will now be checking our options for alternatives. We were going to integrate data from Matomos APIs into our core product and due to that we can't hold it to a lower standard than the rest of our systems.

**Comment by juan131** [comment]
Hi @nielssj 

I didn't know about that article, but just reading this paragraph:

> When Matomo is used behind a load balancer, here are the steps to follow:
>
> 1. **synchronize config/config.ini.php on all servers** – make sure the file config/config.ini.php is the same on all servers (using rsync for example).
> 2. **upload all the Matomo files and all plugins to all servers**, as it is important that all your servers run the same codebase with all features, including any free or premium plugin from the Marketplace.

You can easily identify that synchronisation is needed (same plugins and same configuration across every replica). And, unless you have a NFS system that does it for you, I wouldn't recommend you to replicate Matomo on K8s. The reason is simple, in a K8s world no human intervention should be done in the containers.

**Comment by juan131** [comment]
I will proceed to close this issue, but please feel free to reopen it if you want to continue discussing about scaling Matomo.

**Comment by nielssj** [comment]
I don't fully agree regarding the interpretation of the article.

Having a synchronized configuration file is well supported by K8s and as far as I am aware there are no modern cloud native applications that don’t require some level of config synchronization across replicas. Whether it is provided in a file or an environment variable is not that important. The main differentiator is whether the file needs to be modified by the application during runtime. 

The same can be said about plugin configuration. The article suggests that you can set a flag to block runtime plugin configuration. And based on that you'd simply have to accept a fixed plugin selection or that a new release needs to be pushed to Kubernetes in order to introduce new or remove existing plugins.

In any case, thank you for your perspective 🙏 I won't steal any more of your time.
