### ISSUE TITLE
Provide 'tables_prefix'  config parameter

### ISSUE THREAD

**Issue by sadortun** [bitnami/bitnami-docker-matomo#79]
**Description**
Old Matomo installations use "tables_prefix" set to "piwik_"

**Steps to reproduce the issue:**

**Describe the results you received:**
There is no way of configuring the parameter

**Comment by alemorcuq** [comment]
I've created an internal task to add this, but I can't give you an ETA on this. However, if you want, feel free to create a PR and we will gladly review it.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-matomo#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
