### ISSUE TITLE
Run cron job in a different container

### ISSUE THREAD

**Issue by mbuechner** [bitnami/bitnami-docker-matomo#82]
I'd like to run the cron job `/opt/bitnami/php/bin/php /opt/bitnami/matomo/console core:archiv` in a different container, which uses the volume and database on a shared base. 

For any reason `config.ini.php` is not available within the cron job-container. Why? Is that even possible to do?

**Comment by migruiz4** [comment]
Hi @mbuechner ,

Could you please give us some more details about your use case? 

What configuration are you using for that cronjob-container? 

When using the bitnami/matomo docker image, the archive cronjob can be configured by running the container as root:

https://github.com/bitnami/bitnami-docker-matomo/blob/affdcfc781f73b85e091247f362e16dceb93637e/4/debian-10/rootfs/opt/bitnami/scripts/libmatomo.sh#L218-L225

Also, I'd recommend having a look at this similar issue: https://github.com/bitnami/bitnami-docker-matomo/issues/75

The reason why `config.ini.php` is not showing in the cronjob-container, is because the Runtime configuration of the pod is skipped when using custom commands: 
https://github.com/bitnami/bitnami-docker-matomo/blob/affdcfc781f73b85e091247f362e16dceb93637e/4/debian-10/rootfs/opt/bitnami/scripts/matomo/entrypoint.sh#L20-L31

If you need to configure the cronjob-container, you could load a script (using a volume or a custom image) that did something similar to this and use it as your cronjob-container command:
```bash
#!/bin/bash

. /opt/bitnami/scripts/libmatomo.sh

info "Persisted Matomo installation detected"
# Update default plugins
info "Updating default plugins in persisted data"
rsync -a "$MATOMO_BASE_DIR"/plugins/ "$MATOMO_VOLUME_DIR"/plugins/
info "Restoring Matomo installation"
restore_persisted_app "matomo" "$MATOMO_DATA_TO_PERSIST"
info "Trying to connect to the database server"
db_host="$(ini-file get -s "database" -k "host" "$MATOMO_CONF_FILE")"
db_port="$(ini-file get -s "database" -k "port" "$MATOMO_CONF_FILE")"
is_empty_value "$db_port" && db_port="3306"
db_name="$(ini-file get -s "database" -k "dbname" "$MATOMO_CONF_FILE")"
db_user="$(ini-file get -s "database" -k "username" "$MATOMO_CONF_FILE")"
db_pass="$(ini-file get -s "database" -k "password" "$MATOMO_CONF_FILE")"
matomo_wait_for_db_connection "$db_host" "$db_port" "$db_name" "$db_user" "$db_pass"
 
local -r port="${WEB_SERVER_HTTP_PORT_NUMBER:-"$WEB_SERVER_DEFAULT_HTTP_PORT_NUMBER"}"
info "Configuring cron jobs"
cron_cmd=("${PHP_BIN_DIR}/php" "${MATOMO_BASE_DIR}/console" "core:archive")
generate_cron_conf "matomo" "${cron_cmd[*]} > /dev/null 2>> ${MATOMO_BASE_DIR}/tmp/logs/matomo-cron.log" --run-as "$WEB_SERVER_DAEMON_USER" --schedule "*/1 * * * *"

cron -f
```
This should restore your matomo configuration from the shared volume, check the DB connection, configure the corn and then run cronjob in the foreground so the container doesn't stop.

**Comment by mbuechner** [comment]
Hi @migruiz4,

I'm running the containers on a Kubernetes cluster as non-root. I would like to run one container instance for external access and another instance to do the cron job regularly.  Instance #1 is running non-stop, Instance #2 will be created e.g. ever hour and just run the command `/opt/bitnami/php/bin/php /opt/bitnami/matomo/console core:archiv`. If it's finished the container will be deleted. Both container share the same volume (files) and the same database connection. That's my setup.

I'll try your script and give feedback. Thanks a lot for your help!

**Comment by migruiz4** [comment]
Hi @mbuechner,

Thank you for the information about your use case.

In that case, for other users running into this issue I'd like to clarify that `cron` can not be executed when running the container as non-root because user 1001 does not exist.

So, as you will be running the container regularly, this section of the script:
```
info "Configuring cron jobs"
cron_cmd=("${PHP_BIN_DIR}/php" "${MATOMO_BASE_DIR}/console" "core:archive")
generate_cron_conf "matomo" "${cron_cmd[*]} > /dev/null 2>> ${MATOMO_BASE_DIR}/tmp/logs/matomo-cron.log" --run-as "$WEB_SERVER_DAEMON_USER" --schedule "*/1 * * * *"

cron -f
```
Has to be replaced with the command:
```
info "Running Matomo archive command"
${PHP_BIN_DIR}/php "${MATOMO_BASE_DIR}/console" "core:archive"
```

If you find any further issues let me know.
