### ISSUE TITLE
ERROR PRIVATE DIRECTORIES ARE ACCESSIBLE

### ISSUE THREAD

**Issue by oliworx** [bitnami/bitnami-docker-matomo#89]
**Description**

System check is complaining about “Required Private Directories”

**Steps to reproduce the issue:**

1. install Matomo using the docker image `bitnami/matomo:4.3.1` 
2. run system check `/index.php?module=Installation&action=systemCheckPage&idSite=1&period=day&date=yesterday`

**Describe the results you received:**

ERROR PRIVATE DIRECTORIES ARE ACCESSIBLE

like `/config/config.ini.php` `/lang/en.json` `/tmp/` and so on

**Describe the results you expected:**

No private directories must be accessible

**Additional information you deem important (e.g. issue happens only occasionally):**

I should run the command `console core:create-security-files` 

But this is not possible in a cloud environment with stateless containers!

**Version**

- Output of `docker version`: running on AWS ECS
- Output of `docker info`: running on AWS ECS
- Output of `docker-compose version` (if applicable):

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

running on AWS ECS

**Comment by juan131** [comment]
Hi @oliworx 

The Matomo container was moved to a "non-root" approach some months ago. Find more information in the link below:

- https://github.com/bitnami/bitnami-docker-matomo#3141-debian-10-r79

This means that the container is, by default, using a non-privileged user (`1001` unless modified). 

This approach has several benefits that are described in the guide below:

- https://github.com/bitnami/bitnami-docker-matomo#why-use-a-non-root-container

However, it also has some caveats. As you pointed out, the configuration file is writable by the user running Matomo. Why do we do this? Simply because we're modifying this configuration during the initialization of the container and, therefore, we must guarantee the non-root user has permissions to do so.

**Comment by oliworx** [comment]
@juan131  It is ok the files are writeable.

But these files and directories are exposed to the public, they are accesssible in the web browser!!  
This is just a security-no-go in the area of web applications!  
And the problem could easily be fixed with proper rules in a .htaccess file.

**Comment by amjanoni** [comment]
I'm having the same alert here, I could fix it in the proxy config but would be better have it in the apache config image.

**Comment by juan131** [comment]
I double-checked with @javsalgar and you're right. It seems this test that complains about Matomo configuration was recently added and escaped our test suite.

I will create a task to see if we can run the `console core:create-security-files` during the initialization of Matomo so we can reuse the auto-generated `.htaccess` file to improve the security. Thanks so much for reporting it! 

I will notify you about our progress.

**Comment by pablogalegoc** [comment]
Hi folks! Just to keep you updated, we are currently working on this issue.
