### ISSUE TITLE
Use multiple/different database for each domain to be tracked

### ISSUE THREAD

**Issue by aayush27894** [bitnami/bitnami-docker-matomo#91]
Hello, 

I am currently tracking user metrics for 2 domain names/websites using a single matomo instance. Each of them are being used by different clients. The issue is that all of the data is getting stored in the same database, that might be a security concern for both the clients as both their user data gets stored in the same database and tables. Even though matomo gives a way to isolate the domains at a UI level by creating users to control the access, that isn’t enough.

I was wondering if there is any way of storing the data for each domain that we are tracking to be stored in separate databases and if not separate databases, even separate schemas in the same database should be good enough.

**Comment by carrodher** [comment]
Hi, thanks for using the Bitnami container images.
In this case, I am not very familiar with this specific topic, let's see if someone else in the community has more strong knowledge about Matomo itself. From Bitnami we packaged open-source solutions and provide support related to the infrastructure or customizations, but for specific questions about the application itself, I recommend you try to post the question in a Matomo forum since they are going to be able to provide a better answer about how you can achieve this.

In the end, this container image is using the default Matomo source code, and the docker-compose is using a regular MariaDB database, so if there is a solution for doing that, it should be possible to do it with this container/docker-compose scenario, but the main topic is to know how to do it and, unfortunately, it is something I don't know because I didn't work in deep with the application.

**Comment by oliworx** [comment]
One possible solution: use another Matomo instance (=container ) which is connected to the other Database

**Comment by aayush27894** [comment]
We are trying to go for a multi-tenant architecture design and hence don't want to spin up different instances for different websites.

**Comment by carrodher** [comment]
Maybe using different containers there is an option to solve the issue (although it is not implemented in the container right now). Some applications support database table prefixes, so you can deploy X Matomo containers using different prefixes and all of them connected to the same database, but there are some cons: 1) AFAIK is something not implemented in the container at this moment, and 2) you will need a container per website in order to use different prefixes.

I don't know if you can use different prefixes when configuring the different domains in the same container, this is the way used by other applications to share the same database and differentiate the tables from each instance/domain.

**Comment by aayush27894** [comment]
I am not sure if that's going to be possible given we deploying through K8s. In the ideal scenario I would like to define multiple dbs in the same config file and to be able to tell matomo which website data to store in which database.

**Comment by migruiz4** [comment]
Hi @aayush27894,

I have created an internal task with your feature request. 

Meanwhile, we also accept user contributions so if you'd like to send a PR adding support for multi-tenants we will be happy to review it and help with the release.

**Comment by aayush27894** [comment]
Hi @migruiz4 any update on the feature request?

**Comment by migruiz4** [comment]
Unfortunately, we are unable to provide any ETA for when we expect to start working on this. Please note that we are a small team and have a lot of things on our plate, especially now for summer holidays. 

If you wish, feel free to make a contribution adding support for this feature. You can find the source code for the initialization scripts in the [`rootfs` folder](https://github.com/bitnami/bitnami-docker-matomo/tree/master/4/debian-10/rootfs) in this repo. We'd be glad to help with the review and release!
